[package]
name = "omni"
version = "0.1.0"
edition = "2021"

[dependencies]
safe_drive = "0.4"
motor_lib = {path = "/home/matsuda/morkspace/motor_lib"}
[package.metadata.ros]
safe_drive_version = "0.4"